dist: bionic
language: java
before_install:
- rm ~/.m2/settings.xml
jdk:
- openjdk11
install: ./mvnw -v
script: ./mvnw -B -nsu verify jacoco:report
cache:
  directories:
  - "$HOME/.m2"
branches:
  except:
  - "/^release\\/.*$/"
  - "/^feature\\/.*$/"
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    secure: XaP25HrHzNY4AVcri+upRidHTdJd3Lhnv4TrqwPoasoXem2Puba3VYtmqpp6oITOZwsrthknb4SuuliS+08dd5UpIhHtMiKOV+5I6bb6oXKXYKS5qBzH29PDtvZF8F2wTxDAQNrX3LTQLX1vvkF5UB4i+6OVdZlu2jtmSrAJZEHZNGbqWDbM4wnwjomhdu9lU4LcHoypRME9a1Be6/ZIqtTgGRMcZ5eFcUOO3kw+7E45ntn0i9nTrm1oDrGqEsU1U4Qy7S5mfE2hxDu3XXVRXASEt/NtB0RkR8I9Iomlo8bkaPubLeERoeQFos83Jj4taYnGNA4ZyJNmyS8/TS/yTRW9RGM8UAFAf+DDpmDERUgRRAg8xcz5pmaw8qD8NB056iw1m21z4Q7i0eeOY4yo/u2PwPwW7DG6Ln5TQjWXJKZssNIqZLkIeyYjVyWblsYMHpQjl+FkMtm4f6ywVngkq/v0vr14euUyUhNa/OmqiocRTAsMnod4CVxp4s7PGD64corhW7ewGUACKQu/cX9e4SVUktKurIoJKG0FxQkFCNYhlaKliLNpKtlb2ulYi+xdeIB88cD2SUR7Wm/5M2XFg3iQiOeg04mWBkU23cwxJggJuqsvRuAjPkICcOKsqesFHa49mrQyMNlxM3g9Xi3ytxgTtan0G29sgWARLPfA2VU=
